server.port=${PORT}
thirdeye.uniqueCode=${UNIQUE_CODE}
eureka.client.service-url.defaultZone=${THIRDEYE_RESUME_UPDATER_SERVER_URL}
eureka.instance.hostname=${RENDER_EXTERNAL_HOSTNAME}
eureka.instance.prefer-ip-address=false
eureka.instance.secure-port-enabled=true
eureka.instance.secure-port=443
eureka.instance.non-secure-port-enabled=true

spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.datasource.hikari.maximum-pool-size=8
spring.datasource.hikari.minimum-idle=6
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.max-lifetime=600000
spring.h2.console.enabled=false

spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.username=${REDIS_USERNAME}
spring.data.redis.password=${REDIS_PASSWORD}
spring.data.redis.ssl.enabled=true
spring.cache.redis.time-to-live=600000
spring.data.redis.repositories.enabled=false