spring.application.name=tokenmanager
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
spring.profiles.active=${PROFILE}
eureka.instance.instance-id=${spring.application.name}:${server.port}
eureka.instance.prefer-ip-address=true
thirdeye.timezone = Asia/Kolkata
thirdeye.resume.updater.api.key=${THIRDEYE_RESUME_UPDATER_API_KEY}
spring.data.redis.lettuce.pool.max-active=8
spring.data.redis.lettuce.pool.max-idle=8
spring.data.redis.lettuce.pool.min-idle=2
thirdeye.message.broker.read.rate=10000
thirdeye.redis.balance-prefix=user:tokens:
thirdeye.messagebroker.topics.aiprocesser2.topicName=aiprocesser2
thirdeye.messagebroker.topics.aiprocesser2.topicKey=${AI_PROCESSER2_KEY}
thirdeye.messagebroker.topics.priorityskills.topicName=priorityskills
thirdeye.messagebroker.topics.priorityskills.topicKey=${PRIORITY_SKILL_KEY}
thirdeye.messagebroker.topics.mailprocesser.topicName=mailprocesser
thirdeye.messagebroker.topics.mailprocesser.topicKey=${MAIL_PROCESSER_KEY}
thirdeye.messagebroker.topics.courseprocesser.topicName=courseprocesser
thirdeye.messagebroker.topics.courseprocesser.topicKey=${COURSE_PROCESSER_KEY}
thirdeye.maximumqueries=10
thirdeye.redis.course-prefix=course:buffer:





