spring.application.name=tokenmanager
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
spring.profiles.active=${PROFILE}
eureka.instance.instance-id=${spring.application.name}:${server.port}
eureka.instance.prefer-ip-address=true
thirdeye.timezone = Asia/Kolkata
thirdeye.resume.updater.api.key=${THIRDEYE_RESUME_UPDATER_API_KEY}
spring.data.redis.lettuce.pool.max-active=8
spring.data.redis.lettuce.pool.max-idle=8
spring.data.redis.lettuce.pool.min-idle=2

thirdeye.redis.balance-prefix=user:tokens:
